### ISSUE TITLE
A toggle button for chat alerts

### ISSUE THREAD

**Issue by Techtonic21** [IxGamerXL/Deltustry#24]
It would be annoying to other players that for example, you are constantly farming something and the chat gets filled pretty fast, so I suggest a button to turn off/on the chat alert

**Comment by IxGamerXL** [comment]
Only issue with this is that it could potentially cause some players to use this toggle button to secretly obtain items and such without anyone noticing. If I had the understanding, I would have the mod communicate to other players (if they also had the mod) that they did an action, and they can then look through the most recent logs of player action.

May be possible if I find a way to also add auto PvP interaction.

**Comment by Techtonic21** [comment]
> Only issue with this is that it could potentially cause some players to use this toggle button to secretly obtain items and such without anyone noticing.

Well? Players can already secretly obtain items by going into single player

**Comment by IxGamerXL** [comment]
This has been finished in development. It has become a setting in the game (found within Settings in the mod's dialog), and will send a message of notice for when you toggle it on or off. ASimpleMindustryPlayer can fix this of course, but he's likely going to die inside trying to implement his edits lol.
