### ISSUE TITLE
Skip Turn Button

### ISSUE THREAD

**Issue by Techtonic21** [IxGamerXL/Deltustry#25]
Idk, would be more convenient than spamming the guard button for search farming

**Comment by IxGamerXL** [comment]
How does this fix spamming Guard?

**Comment by Techtonic21** [comment]
> How does this fix spamming Guard?

Idk, skipping does nothing while spamming guard makes you super stronk, and I don't want to be super stronk bcuz of farming items

**Comment by Techtonic21** [comment]
Optional: Make the misc items work when skipping turns too (cuz guard spamming makes you unaffected by attacks for a few turns and that's not very fair is it?)

**Comment by IxGamerXL** [comment]
For v1.5.0, I am going to nerf Guard from bulking into invincible territory by preventing guard effects from stacking. Possibly too critical, so I might do that as a last v1.4 update in the mod's timeline.

**Comment by Techtonic21** [comment]
> For v1.5.0, I am going to nerf Guard from bulking into invincible territory by preventing guard effects from stacking, so this suggestion may end up obsolete if it doesn't seem to be deemed useful by then.

If that's the case then this suggestion may be pointless now, I think this issue can be closed if you desire

**Comment by IxGamerXL** [comment]
> > For v1.5.0, I am going to nerf Guard from bulking into invincible territory by preventing guard effects from stacking, so this suggestion may end up obsolete if it doesn't seem to be deemed useful by then.
> 
> If that's the case then this suggestion may be pointless now

I didnt notice your comment until i just posted so i edited btw

**Comment by Techtonic21** [comment]
> > > For v1.5.0, I am going to nerf Guard from bulking into invincible territory by preventing guard effects from stacking, so this suggestion may end up obsolete if it doesn't seem to be deemed useful by then.
> > 
> > 
> > If that's the case then this suggestion may be pointless now
> 
> I didnt notice your comment until i just posted so i edited btw

Lmao
