### ISSUE TITLE
Bug: Scrap Fry Crash

### ISSUE THREAD

**Issue by notMEEPoffaith** [IxGamerXL/Deltustry#29]
**What is the bug causing?**

> It causes the game to crash.

**How do you recreate the bug?**

> Step 1: Eat scrap fries.

**Comment by IxGamerXL** [comment]
Resolved in the development version of the mod. Turns out it was because of the item giving **Infinity** HP and MP, so I simply nerfed it so it works properly. You'll see the fix later on once I get everything wrapped.
